import { copyFileSync, cpSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const [, , workDir] = process.argv;
if (!workDir) { console.error('usage: node build-run-dir.mjs <work-dir>'); process.exit(2); }

// meta.json is REQUIRED by the Hyperframes studio for project identification —
// without it, the studio cannot detect the project and `npx hyperframes preview`
// shows a disabled play button. hyperframes.json carries paths config; DESIGN.md
// is helpful context for AI agents iterating in the run-dir.
// audio-preview.html is the synced video+audio preview shell that bypasses the
// HF studio iframe cold-load race (which silently leaves voiceover unplayed);
// served at /api/projects/<run-id>/preview/audio-preview.html.
for (const f of ['meta.json', 'hyperframes.json', 'DESIGN.md', 'audio-preview.html']) {
  if (existsSync(f)) copyFileSync(f, join(workDir, f));
}
if (existsSync('assets')) cpSync('assets', join(workDir, 'assets'), { recursive: true });
// compositions/ is generated by the yt-compose skill (v4: 5 per-scene files).
// Do NOT copy project-root compositions/ — those are HF-init scaffolding
// (captions.html, cinematic-zoom.html, graphics.html, sdf-iris.html) which
// would clutter the studio sidebar. We just make sure the dir exists.
mkdirSync(join(workDir, 'compositions'), { recursive: true });
mkdirSync(join(workDir, 'renders'), { recursive: true });
mkdirSync(join(workDir, 'snapshots'), { recursive: true });
console.log(`OK run dir prepared at ${workDir}`);
